/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofc;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class PBaseDatos extends javax.swing.JFrame {

    /**
     * Creates new form PBaseDatos
     */
    public PBaseDatos() {
        //super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botVerComp = new javax.swing.JButton();
        botVerArq = new javax.swing.JButton();
        botAddComp = new javax.swing.JButton();
        botAddArq = new javax.swing.JButton();
        botHome = new javax.swing.JButton();
        botAddArq1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Base de Datos");
        setResizable(false);

        botVerComp.setText("Competiciones");
        botVerComp.setToolTipText("Competiciones");
        botVerComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVerCompActionPerformed(evt);
            }
        });

        botVerArq.setText("Arqueros");
        botVerArq.setToolTipText("Arqueros");
        botVerArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVerArqActionPerformed(evt);
            }
        });

        botAddComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofc/Ico_add.png"))); // NOI18N
        botAddComp.setText("Nueva Competición");
        botAddComp.setToolTipText("Nueva Competición");
        botAddComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAddCompActionPerformed(evt);
            }
        });

        botAddArq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofc/Ico_add.png"))); // NOI18N
        botAddArq.setText("Nuevo Arquero");
        botAddArq.setToolTipText("Nuevo Arquero");
        botAddArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAddArqActionPerformed(evt);
            }
        });

        botHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofc/Ico_home.png"))); // NOI18N
        botHome.setToolTipText("Volver a Inicio");
        botHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botHomeActionPerformed(evt);
            }
        });

        botAddArq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofc/Ico_add.png"))); // NOI18N
        botAddArq1.setText("Nueva Puntuación");
        botAddArq1.setToolTipText("Nueva Puntuación");
        botAddArq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAddArq1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botHome, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botAddComp)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(botVerComp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botAddArq)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botVerArq)
                                .addGap(45, 45, 45)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botAddArq1)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botHome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botVerComp)
                    .addComponent(botVerArq))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAddComp)
                    .addComponent(botAddArq))
                .addGap(18, 18, 18)
                .addComponent(botAddArq1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botVerCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVerCompActionPerformed
        try {
            this.setVisible(false);
            pVistaArqueros pva = new pVistaArqueros(false);
            pva.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PBaseDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botVerCompActionPerformed

    private void botVerArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVerArqActionPerformed
        try {
            this.setVisible(false);
            pVistaArqueros pva = new pVistaArqueros(true);
            pva.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PBaseDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botVerArqActionPerformed

    private void botAddCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAddCompActionPerformed
        this.setVisible(false);
        nuevaComp na = new nuevaComp();
        na.setVisible(true);
    }//GEN-LAST:event_botAddCompActionPerformed

    private void botAddArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAddArqActionPerformed
        this.setVisible(false);
        nuevoArq nc = new nuevoArq();
        nc.setVisible(true);
    }//GEN-LAST:event_botAddArqActionPerformed

    private void botHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botHomeActionPerformed
        PInicio pIn = new PInicio();
        pIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botHomeActionPerformed

    private void botAddArq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAddArq1ActionPerformed
        try {
            this.setVisible(false);
            AddPunt ap = new AddPunt();
            ap.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PBaseDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botAddArq1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PBaseDatos dialog = new PBaseDatos();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAddArq;
    private javax.swing.JButton botAddArq1;
    private javax.swing.JButton botAddComp;
    private javax.swing.JButton botHome;
    private javax.swing.JButton botVerArq;
    private javax.swing.JButton botVerComp;
    // End of variables declaration//GEN-END:variables

}
